# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04c491a2c94b80581991c67cde20b949b30af44d08c4c613f10b9a3ac05b3193030d262800c26c0dc3ebfb07abe9d3d52352ad560ba0e0a318cc0b43a121d913

test:
  secret_key_base: e34c69bf8cc305cf034b2dac6d31e1e8f82e221a2327560819ab5d50027a96ee8972a875218185c07c98e638ef75f19315f27db5577c92b390b0a94606b6e47d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
